name: Classroom Workflow

on:
  push:
    paths:
      - 'scripts/session_6/hello_world.txt'
  pull_request:
    paths:
      - 'scripts/session_6/pull_request_test.txt'

jobs:
  classroom_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print latest content
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push"]; then
            cat scripts/session_6/hello_world.txt
          else [ "$GITHUB_EVENT_NAME" == "pull_request"]; then
            cat scripts/session_6/pull_request_test.txt
          fi
