name: Classroom Workflow

on:
  push:
    paths:
      - 'scripts/session_6/hello_world.txt'

jobs:
  classroom_job:
    runs-on: ubuntu-lastest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3 
      - name: Print latest content
        run: cat scripts/session_6/hello_world.txt 
        